services:
  ynym-portal-db:
    image: postgres:15.7
    container_name: ynym-portal-db
    hostname: ynym-portal-db
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --locale=C
      - PGTZ=Asia/Tokyo
      - TZ=Asia/Tokyo
    ports:
      - 5432:5432
    volumes:
      - ynym-portal-db-volume:/var/lib/postgresql/data

volumes:
  ynym-portal-db-volume:
    name: ynym-portal-db-volume
    driver: local

networks:
  default:
    name: ynym-portal-network
    external: true
